# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: text2image.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'text2image.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10text2image.proto\x12\ntext2image\"F\n\x0cImageRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x02 \x01(\t\x12\x17\n\x0fnegative_prompt\x18\x03 \x01(\t\"u\n\rImageResponse\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x14\n\x0cimage_base64\x18\x02 \x01(\t\x12\x12\n\x06status\x18\x03 \x01(\tB\x02\x18\x01\x12\x13\n\x0bstatus_code\x18\x04 \x01(\x05\x12\x15\n\rresponse_json\x18\x05 \x01(\t2Z\n\x12TextToImageService\x12\x44\n\rGenerateImage\x12\x18.text2image.ImageRequest\x1a\x19.text2image.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'text2image_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGERESPONSE'].fields_by_name['status']._loaded_options = None
  _globals['_IMAGERESPONSE'].fields_by_name['status']._serialized_options = b'\030\001'
  _globals['_IMAGEREQUEST']._serialized_start=32
  _globals['_IMAGEREQUEST']._serialized_end=102
  _globals['_IMAGERESPONSE']._serialized_start=104
  _globals['_IMAGERESPONSE']._serialized_end=221
  _globals['_TEXTTOIMAGESERVICE']._serialized_start=223
  _globals['_TEXTTOIMAGESERVICE']._serialized_end=313
# @@protoc_insertion_point(module_scope)
